
# Unified configuration for SMILES Block-Diffusion (v4)
paths:
  train_path: ./data/tiny-pubchem-smiles/train-00000-of-00001.parquet
  valid_path: ./data/tiny-pubchem-smiles/validation-00000-of-00001.parquet
  vocab_path: ./vocab.txt
  save_dir: ./checkpoints

model:
  max_len: 64 # 1024
  d_model: 512  # 词嵌入纬度
  n_heads: 8
  n_layers: 8
  dropout: 0.1
  tie_weights: true

train:
  epochs: 100
  batch_size: 50
  lr: 3.0e-4
  beta: 0.3
  omega: 0.8
  grad_clip: 1.0  # 梯度裁剪
  num_workers: 8  # 用多少个子进程来加载数据, 8, 16
  device: auto

sample:
  steps: 24
  top_p: 0.9
  device: auto
