
# Unified configuration for SMILES Block-Diffusion (v4)
paths:
  train_path: ./data/DrugLikeSMILSE-debug/train
  valid_path: ./data/DrugLikeSMILSE-debug/validation
  vocab_path: ./vocab.txt
  save_dir: ./checkpoints

model:
  max_len: 64 # 1024
  d_model: 768 # 词嵌入纬度
  n_heads: 12
  n_layers: 12
  dropout: 0.1
  tie_weights: true

train:
  epochs: 50
  batch_size: 280
  lr: 3.0e-4
  beta: 0.3
  omega: 0.8
  grad_clip: 1.0  # 梯度裁剪
  num_workers: 8  # 用多少个子进程来加载数据, 8, 16
  device: auto

sample:
  steps: 24
  top_p: 0.9
  device: auto
