paths:
  data_dir: /data/yqw/smiles-bd/data/DrugLikeSMILSE-debug
  cache_dir: /data/yqw/smiles-bd/cache/cache-DrugLikeSMILSE-debug
  vocab_path: ${PWD}/vocab.txt
  save_dir: ${PWD}/checkpoints

data:
  text_column: input         # column name in HF dataset or text dataset
  num_workers: 8
  insert_special_tokens: true

model:
  max_len: 66
  d_model: 512
  n_heads: 8
  n_layers: 8
  dropout: 0.1
  tie_embeddings: true
  sdpa_backend: auto    # auto|math|mem_efficient|flash

train:
  seed: 1337
  lr: 3e-4
  beta: 0.3
  omega: 0.8
  grad_clip: 1.0
  batch_size: 32
  grad_accum_steps: 1
  amp: auto             # auto|bf16|fp16|off
  compile: true         # 图编译  稳定后开（长跑）
  compile_mode: reduce-overhead
  tf32: true
  eval_subset_ratio: 0.1


  # iteration-based control
  max_iters: 10000
  eval_interval: 500
  save_interval: 500

sample:
  steps: 24
  top_p: 0.9
