paths:
  data_dir: /data/yqw/smiles-bd/data/DrugLikeSMILSE-debug
  cache_dir: ${PWD}/cache/cache-DrugLikeSMILSE-debug
  vocab_path: ${PWD}/vocab.txt
  save_dir: ${PWD}/checkpoints

data:
  text_column: input         # column name in HF dataset or text dataset
  num_workers: 8

model:
  max_len: 64
  d_model: 512
  n_heads: 8
  n_layers: 8
  dropout: 0.1

train:
  seed: 1337
  lr: 3e-4
  beta: 0.3
  omega: 0.8
  grad_clip: 1.0
  batch_size: 32
  grad_accum_steps: 1
  amp: auto              # auto|bf16|fp16|off
  compile: false         # 图编译  稳定后开（长跑）
  compile_mode: reduce-overhead
  sdpa_backend: auto 
  tf32: true


  # iteration-based control
  max_iters: 100000
  log_interval: 10
  eval_interval: 2000
  save_interval: 2000

sample:
  device: auto
  steps: 24
  top_p: 0.9
